#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

changed_files=$(git diff --cached --diff-filter=d --name-only)
if [ $? -eq 1 ]; then
  echo $changed_files
  npm run lint:fix $changed_files
  git add $changed_files
fi

