#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

changed_files=$(git diff --cached --diff-filter=d --name-only)
if [ "$changed_files" ]; then
	for f in $changed_files
  do
    npm run lint:fix --files "$f"
    git add "$f"
  done
fi

